# Generated by Django 4.2.3 on 2023-07-07 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='official_image',
            field=models.ImageField(blank=True, null=True, upload_to='home_images'),
        ),
    ]
