# Generated by Django 4.2.3 on 2023-07-12 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_home_official_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unofficial_image', models.ImageField(blank=True, null=True, upload_to='about_images')),
            ],
        ),
    ]
