# Generated by Django 4.2.3 on 2023-07-14 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='subtopics',
            field=models.ManyToManyField(blank=True, to='core.skill'),
        ),
    ]
