# Generated by Django 4.2.3 on 2023-07-14 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_skill_subtopics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='subtopics',
        ),
        migrations.AddField(
            model_name='skill',
            name='parent_skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subskills', to='core.skill'),
        ),
    ]
