# Generated by Django 4.2.3 on 2023-07-17 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_skill_subtopics_skill_parent_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillCartegory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='skill',
            name='parent_skill',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='skill_type',
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AddField(
            model_name='skill',
            name='skillcartegory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='core.skillcartegory'),
        ),
    ]
