# Generated by Django 4.2.3 on 2023-07-17 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_skillcartegory_remove_skill_parent_skill_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SkillCartegory',
            new_name='SkillCategory',
        ),
        migrations.AlterModelOptions(
            name='skillcategory',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.RenameField(
            model_name='skill',
            old_name='skillcartegory',
            new_name='skillcategory',
        ),
    ]
