# Generated by Django 4.2.3 on 2023-07-17 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_skillcartegory_skillcategory_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skillcategory',
            options={'verbose_name_plural': 'Skill Categories'},
        ),
    ]
