# Generated by Django 4.2.3 on 2023-07-20 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_skillcategory_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='background_image',
        ),
    ]
