# Generated by Django 4.2.3 on 2023-07-22 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_resume_alter_about_options_alter_home_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Resume',
            new_name='Education',
        ),
        migrations.AlterModelOptions(
            name='education',
            options={'verbose_name_plural': 'Education'},
        ),
    ]
