# Generated by Django 4.2.3 on 2023-07-22 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_rename_resume_education_alter_education_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_name', models.CharField(max_length=255)),
                ('work_mode', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('company_location', models.CharField(blank=True, max_length=255, null=True)),
                ('work_description', models.TextField()),
                ('period', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Resume Section: Work Experience',
            },
        ),
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name_plural': 'About Section'},
        ),
        migrations.AlterModelOptions(
            name='education',
            options={'verbose_name_plural': 'Resume Section: Education'},
        ),
        migrations.AlterModelOptions(
            name='home',
            options={'verbose_name_plural': 'Home Section'},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'verbose_name_plural': 'Skill Section: Skills'},
        ),
        migrations.AlterModelOptions(
            name='skillcategory',
            options={'verbose_name_plural': 'Skill Section: Skill Categories'},
        ),
    ]
