# Generated by Django 4.2.3 on 2023-07-27 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_experience_alter_about_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='education_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='work_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
