# Generated by Django 4.2.3 on 2023-08-03 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_education_education_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Resume Section: Education'},
        ),
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Resume Section: Work Experience'},
        ),
        migrations.AddField(
            model_name='education',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
