# Generated by Django 4.2.3 on 2023-08-07 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_toolsused_alter_project_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name_plural': 'ABOUT SECTION'},
        ),
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'RESUME SECTION: Education'},
        ),
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'RESUME SECTION: Work Experience'},
        ),
        migrations.AlterModelOptions(
            name='home',
            options={'verbose_name_plural': 'HOME SECTION'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name_plural': 'PROJECTS SECTION: Project'},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'verbose_name_plural': 'SKILL SECTION: Skills'},
        ),
        migrations.AlterModelOptions(
            name='skillcategory',
            options={'verbose_name_plural': 'SKILL SECTION: Skill Categories'},
        ),
        migrations.AlterModelOptions(
            name='toolsused',
            options={'verbose_name_plural': 'PROJECTS SECTION: Tools and Technologies Used'},
        ),
        migrations.AlterField(
            model_name='project',
            name='tools_and_lang',
            field=models.ManyToManyField(blank=True, max_length=255, to='core.toolsused'),
        ),
        migrations.AlterField(
            model_name='toolsused',
            name='tools_name',
            field=models.CharField(max_length=100),
        ),
    ]
