# Generated by Django 4.2.3 on 2023-08-07 04:29

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_about_options_alter_education_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
