# Generated by Django 4.2.3 on 2023-08-14 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_description',
        ),
        migrations.AddField(
            model_name='project',
            name='github_readme_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
