# Generated by Django 4.2.7 on 2023-12-08 14:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_blog_card_intro_blog_blog_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-blog_date_for_ordering'], 'verbose_name_plural': 'BLOGS SECTION'},
        ),
        migrations.AddField(
            model_name='blog',
            name='blog_date_for_ordering',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
